### ISSUE TITLE
typescript support?

### ISSUE THREAD

**Issue by zynth17** [justintaddei/v-shared-element#161]
hello, thankyou for this amazing library. will you support typescript ? i got an error using vue 3 with typescript 

![image](https://user-images.githubusercontent.com/45350572/161253607-b0e1d82a-5357-4f70-8411-1148ad276b69.png)

**Comment by justintaddei** [comment]
That is rather strange. Is it possible that the issue is with your configuration?  Literally the entire library is written in typescript :)

Would you mind sharing your `tsconfig.json`?

**Comment by zynth17** [comment]
> That is rather strange. Is it possible that the issue is with your configuration? Literally the entire library is written in typescript :)
> 
> Would you mind sharing your `tsconfig.json`?

here is the repro

https://stackblitz.com/edit/vitejs-vite-wapqn9?file=src/main.ts

**Comment by justintaddei** [comment]
Thank you. I will investigate what's going on.

It's odd that it doesn't work. My first thought was that `moduleResolution` was not set to `"node"`, but it is. Here's a local project of mine using `v-shared-element@3.1.0`
![image](https://user-images.githubusercontent.com/16705594/161294345-c6112bed-5cfc-438d-b4d9-e2c3064645b2.png)

**Comment by justintaddei** [comment]
I downloaded the project from stackblitz.com, ran `npm i` and it appears to be working as intended without modification:
![image](https://user-images.githubusercontent.com/16705594/161296268-6675725c-8951-44b5-9006-8df90a1b0f94.png)

![image](https://user-images.githubusercontent.com/16705594/161296386-289e68db-8575-4bfc-8852-aa0b8ef6093c.png)

I believe any issue there maybe is with the way stackblitz handles ts imports. I see the error on stackblitz.com, but not with an identical configuration on my machine.
