### ISSUE TITLE
using keep-alive causes the transition to only be run once

### ISSUE THREAD

**Issue by 719media** [justintaddei/v-shared-element#2]
Using `<keep-alive>` makes the transition only run once, and then never again for that namespace.

There are a lot of reasons people may use `<keep-alive>`, but mine is because the "parent component" uses infinite scrolling and additional content is loaded through ajax... so I want the user to be able to return to where they were without reloading the component from scratch.

**Comment by justintaddei** [comment]
I fixed the flickering on the example page. Turns out it was a 404 error caused because I wasn't respecting the base route. (In other words it wasn't an issue with the plugin. See commit #6fb1594 for the relevant changes)

Are you seeing the flickering you mentioned in your project as well?

**Comment by justintaddei** [comment]
New proposal:

After testing some more I found the `beforeEach` route guard is still called. This means we only need to worry about the `activated` hook.

How would something like this work for your use case:
```vue
<template>
  <ul>
    <li
      v-for="item in items"
      :key="item.id"
      v-shared-element:id="{
        registerKeepAliveHooks,
      }"
    >
        {{ item.title }}
    </li>
  </ul>
</template>

<script>    
export default {
    data() {
        return {
            sharedElementHooks: [],
            items: [],
            isFirstRender: true
        }
    },

    methods: {
        registerKeepAliveHooks(activate) {
            this.sharedElementHooks.push(activate)
        }
    },

    activated() {
        // We need a flag here because
        // both created() and activated()
        // are called for the first component render 
        if (!this.isFirstRender)
            this.sharedElementHooks.forEach(activate => activate())
    },

    deactivated() {
        this.isFirstRender = false
    }
}
</script>
```

**Comment by 719media** [comment]
So I went and created this scenario here. Helped me think about how I would use this.

https://codesandbox.io/s/sharedelementtransition-keep-alive-nicrg?file=/src/views/Home.vue

I'm not exactly sure what "activate" is tying into on the directive side, but perhaps if it could be used for more than "keep-alive" (it is just firing the transition based on state data) you could name it something more abstract (e.g. `registerTransitionHook` instead of `registerKeepAliveHooks`). Thought here is you could potentially fire the transition on something more manual if there were other hooks to tie into down the road.

It annoys me to have to track the isFirstRender, maybe there is the option to not start the animation automatically (e.g. new `startOnInsert` boolean...):

```
<template>
  <ul>
    <li
      v-for="item in items"
      :key="item.id"
      v-shared-element:id="{
        registerKeepAliveHooks,
        startOnInsert: false,
      }"
    >
        {{ item.title }}
    </li>
  </ul>
</template>

<script>    
export default {
    data() {
        return {
            sharedElementHooks: [],
            items: [],
        }
    },

    methods: {
        registerKeepAliveHooks(activate) {
           // if this was not here, then the transition would never start
            this.sharedElementHooks.push(activate)
        }
    },

    activated() {
        this.sharedElementHooks.forEach(activate => activate())
    },
}
</script>
```

**Comment by justintaddei** [comment]
I really like that `startOnInsert` idea. It really cleans it up. The other boolean options all default to `false` so maybe `waitForTransitionHook` or similar to keep it consistent?


`activate` is just reusing the `inserted` hook from Vue. In theory, as long as the transition hook is fired after the beforeEach route guard is called everything should work regardless of which hook is used. Do you like `registerTrigger` or `registerTransitionTrigger`? It occurred to me that it is more of a trigger than a hook since the user is the one calling it.

The only change under the hood was this:

```js
if (binding.value?.registerActivatedHook)
        binding.value.registerActivatedHook(() => {
            // `inserted` is Vue's directive lifecycle hook. I'm just manually calling it.
            inserted(activeElement, binding, vnode)
        })
```

**Comment by 719media** [comment]
Ok cool makes sense. Perhaps name them the same?
If `waitForTrigger` then `registerTrigger` ?

**Comment by justintaddei** [comment]
Yeah, that seems logical to me.

What I would like is to have some sort of helper function to handle the boilerplate for you.

What do you think of something like this? I'm just not sure how to keep this separate between components though...
```js
import {registerTrigger, activateTriggers} from 'v-shared-element'

. . .

methods: {
    registerTrigger
},

activated() {
    activateTriggers()
},
```

**Comment by justintaddei** [comment]
Maybe this:

```js
import {storeTrigger, activateTriggers} from 'v-shared-element'

. . .

data() {
    return {
        triggers: []
    }
},

methods: {
    registerTrigger: trigger => storeTrigger(trigger, this.triggers)
},

activated() {
    activateTriggers(this.triggers)
},
```

**Comment by 719media** [comment]
I don't know, comparing that to
```
data() {
  return {
    triggers: [],
  }
},

methods: {
  registerKeepAliveHooks(activate) {
    this.triggers.push(activate)
  }
},

activated() {
  this.triggers.forEach(activate => activate())
},
```

Not really saving you from anything IMO... but I understand using a common method to create a standard implementation. Just strange you have two new methods, one of which just does arg2.push(arg1), and the other which just does arg1.forEach(f => f())

Seems kind of... unnecessary. Especially when you are having to create the data field. Perhaps you could do a mixin instead (see https://vuejs.org/v2/guide/mixins.html) and then it's just
```
//provided by v-shared-element
const triggerMixin = {
  ...
  data() {
    return {
      $_vSharedElement_triggers: [],
       // see https://vuejs.org/v2/style-guide/#Private-property-names-essential
    };
  },
  methods: {
    $_vSharedElement_registerTriggers() {
      // stuff
    },
    $_vSharedElement_activateTriggers() {
      // stuff
    },
  },
  activated() {
    this.$_vSharedElement_activateTriggers(this.$_v_shared_element_triggers);
  },
}
```

```
import { triggerMixin } from 'v-shared-element'

export default {
  mixins: [ triggerMixin ],
}

...
<div
  v-shared-element:id="{
    useMixin: true,
  }"
>
```

I'm not sure I like this approach... it's too... specific and just feels a little wonky

**Comment by justintaddei** [comment]
There's also the problem of actually getting the triggers from each directive. If we go with a mixin, how would we do that? (Without resorting to the user defined "callback getter function thing" that we started with?

**Comment by 719media** [comment]
I rewrote the directive as a component, and hooked into the activated() hook
I'm sure it could be improved (I ripped out the typescript for quick demo purposes), and perhaps it would be better to have the component be a functional component without any template... not sure. As in
```
<v-shared-element tag="img">
</v-shared-element>
```
vs
```
<v-shared-element>
  <img>
</v-shared-element>
```

I wrote it like router-link (using the former component-has-root-node style), and I think I prefer it like that...

https://codesandbox.io/s/sharedelementtransition-component-3ef8h

**Comment by 719media** [comment]
One problem I run into is when you only cache "some" of the keep-alive, e.g.
```
<keep-alive include="Home">
```
I'm not sure the best way to "fire on mounted, or activated, but not both in the same render", when any component could be mounted only (no keep-alive), mounted and activated (keep-alive first time), or activated only (keep-alive 2+ time)

**Comment by justintaddei** [comment]
Well, that certainly fixes the problem. I didn't use a component originally because I felt it cluttered the markup and makes integrating it into an existing project harder (sort of). What would you think about shipping both the directive and the component? To me, that seems a little confusing but it's definitely an option to consider. Last night I came up with the following idea that still uses the directive approach. Let me know what you think.

```vue
<template>
  <ul>
    <li
      v-for="item in items"
      :key="item.id"
      v-shared-element:id="{
        $keepSharedElementAlive // <- there's probably a better name.
      }"
    >
        {{ item.title }}
    </li>
  </ul>
</template>

<script>    
import {sharedElementMixin} from 'v-shared-element'

export default {
    mixins: [sharedElementMixin]
}
</script>
```

`$keepSharedElementAlive` is basically the `registerTrigger` from before.

Mixin:
```js
//provided by v-shared-element
export const sharedElementMixin = {
  ...
  data() {
    return {
      $_vSharedElement_triggers: [],
       // see https://vuejs.org/v2/style-guide/#Private-property-names-essential
    };
  },
  methods: {
    $keepSharedElementAlive(trigger) {
        this.$_vSharedElement_triggers.push(trigger)
    }
  },
  activated() {
   this.$_vSharedElement_triggers.forEach(trigger => trigger())
  },
}
```

**Comment by justintaddei** [comment]
As for the component approach,

> "fire on mounted, or activated, but not both in the same render"

A simple `shouldFireOnActivated` flag that is set to `true` the first time `activated` is called would work, wouldn't it?

```js
. . .
activated() {
    if (!this.shouldFireOnActivated) return
    
    . . .
}
. . .
```

**Comment by justintaddei** [comment]
I'm working on an example of the directive approach now. Will be ready shortly

**Comment by 719media** [comment]
OK cool.
Regarding

> As for the component approach,
> 
> > "fire on mounted, or activated, but not both in the same render"
> 
> A simple `shouldFireOnActivated` flag that is set to `true` the first time `activated` is called would work, wouldn't it?
> 
> ```js
> . . .
> activated() {
>     if (!this.shouldFireOnActivated) return
>     
>     . . .
> }
> . . .
> ```

Sometimes I have behavior in vue where the activated hook is called immediately after mounted. And sometimes it is not called until the component is actually "navigated to" the 2nd+ time. It is unexpected, as definitely in codesandbox it is always firing activated the same time as mounted in examples there, so trying to figure out how to reproduce

**Comment by justintaddei** [comment]
Here's the directive way of doing it: https://codesandbox.io/s/v-shared-elementmixin-d81g6

I think this looks pretty good. It is a little specific like you said earlier but I'm not sure that's a bad thing. We could always make a `registerGenericTrigger` method to allow for custom behavior.

**Comment by justintaddei** [comment]
That's really strange. I would've thought it was more predictable. Let me know what you find out.

Here's the directive way of doing it: https://codesandbox.io/s/v-shared-elementmixin-d81g6

I think this looks pretty good. It is a little specific like you said earlier but I'm not sure that's a bad thing. We could always make a `registerGenericTrigger` method to allow for custom behavior.

**Comment by justintaddei** [comment]
Mixin: 
```js
export const sharedElementMixin = {
  data() {
    return {
      $_vSharedElement_triggers: [],
      $_vSharedElement_firstRender: true
    };
  },
  methods: {
    $keepSharedElementAlive(trigger) {
      this.$data.$_vSharedElement_triggers.push(trigger);
    }
  },
  activated() {
    if (this.$data.$_vSharedElement_firstRender)
      return (this.$data.$_vSharedElement_firstRender = false);

    this.$data.$_vSharedElement_triggers.forEach(trigger => trigger());
  }
};
```

In the directive's inserted hook:
```js
const inserted = async (
      activeElement,
      binding,
      vnode,
      _,
      synthetic = false
    ) => {
      const combinedOptions = {
        ...DEFAULT_OPTIONS,
        ...options,
        ...binding.value
      };

      if (!synthetic && typeof binding.value?.$keepSharedElementAlive === 'function') {
        binding.value.$keepSharedElementAlive(() => {
          inserted(activeElement, binding, vnode, null, true);
        });
      }

      // v-shared-element:id
      const id = binding.arg;
      if (!id)
        throw new Error(
          `Missing ID on a v-shared-element. For usage see: https://github.com/justintaddei/v-shared-element#readme`
        );

 . . .
```

**Comment by 719media** [comment]
OK cool, looks good. I agree having both component and mixin seems like overkill, double code to manage, double bug reports, etc.

**Comment by justintaddei** [comment]
Okay so we're going forward with the directive+mixin then?

I think it's pretty much complete except some types and the `registerGenericTrigger` (although now that I'm thinking about it, simply `registerTrigger` is probably better).
