### ISSUE TITLE
Performance issues when dealing with many shared-elements

### ISSUE THREAD

**Issue by Chaphasilor** [justintaddei/v-shared-element#20]
So, as promised, here's my issue:

When there are 'long' transitions from v-shared-element, the `SharedElementRouteGuard` inside the router will prevent the route change until the transitions are done.  
But not only that, there's also a noticeable delay *before* the transition starts in the first place. I'm guessing this is due to `illusory` elements being created and prepared for transitioning.  
This can take quite some time and is very noticeable, especially when `click` events are delayed by it.

Here's a video of the issue: https://streamable.com/l5vm0f (the circled areas are where I clicked, you can see the delay between the touch indicator and the transition starting) 

This seems like a problem with performance (the delay is longer on my phone compared to my laptop).
Maybe you could optimize things a bit more, or see if there are any 'expensive' transitions which should be avoided?

Also, how about instead of waiting for the transition *before* changing the page, you just transition *after* the new route is mounted? This might at least improve *perceived* performance...

**Comment by justintaddei** [comment]
It's interesting that you would say it's waiting before doing the route change. Are you sure that is what's happening or could it just be the main thread blocked?

`next()` is called immediately after the elements are cloned.  
[See here](https://github.com/justintaddei/v-shared-element/blob/f42efc72e4d00660f7e32c68eb681c28db11e340/src/routeGuard.ts#L58)

Are you using `restrictToViewport`? That could help you a lot with such a long list. If it doesn't provide enough of a performance gain I'll investigate other ways to speed it up.

The main bottleneck is that I have to clone every shared-element on the route you're leaving because there's no way know which of them will be present on the next route. One thing I just thought of as a possible workaround is some kind of optional route-filter.

Something like this:

```js
routes: ["/about"]
````

or

```js
routes: (path, id) => path.endsWith(id)
```

 The benefit is it would reduce a lot of the overhead introduced by the cloning stage. The downside would be messy markup. If you have a better idea, let me know.

**Comment by Chaphasilor** [comment]
It *feels* like it's just waiting, but it's probably busy as hell (as I said, performance issue, with shorter delays on faster hardware).

I'm already using `restrictToViewport`. It probably won't help much anyway, given that seven items are on screen anyway...

How about you clone the elements when the app is idle (and after changes to the elements)? Then when the user navigates, you already have all elements cloned and ready to go?

**Comment by justintaddei** [comment]
Hmm. That would be ideal but I don't think it's possible to pull off reliably. A directive (in Vue 2 anyway) can't detect updates on the element it's bound to. And even with Vue 3's `componentUpdated` hook I wouldn't be able to detect style changes.

Out of curiosity, what phone are you testing on?

**Comment by Chaphasilor** [comment]
I'm testing on a OnePlus 5 :)

Opt-in might be worth a shot. You mean enabling pre-copying manually on a per-element basis, right?

**Comment by justintaddei** [comment]
Yes, or globally.

What do you think of the route-filter idea? I was typing on my phone earlier so I didn't include a very good example. Here's what I'm thinking:

```vue
<Component
  v-shared-element:[`download-${id}`]="{
    // Only clone this element if the next route is /about or /details.
    restrictToRoutes: ['/about', '/details']
    // Or, use a function to determine if this element should be cloned.
    // `route` is vue-router's '$route' object and `id` is the id of this shared element (the same one used as the directive arg).
    restrictToRoutes: (route, id) => id.includes(route.params.id)
  }"
/>
```

Doing it this way would mean that the only item in your list that would be cloned would be the one you're expanding. And, when you go to the settings page none of the list items would be cloned.

**Comment by Chaphasilor** [comment]
Well the thing is, if I can write a function to determine if the cloned element exists on the destination route, so can you (more or less).

What I mean by that is that I would simply compare the id I use for the `v-shared-element` identifier to the id in the route (at least for this example).

This is so easy that I believe this could be somehow automated, maybe by changing the way the identifier is used by the directive?

I'm thinking of something more global, so that you can use the router guard to check if the element exists on the destination route...  
Would that be possible? Or does it have to be a custom function?

**Comment by justintaddei** [comment]
The problem with having an internal compare function like that is that it I don't know how someone will architect their routes, so I can't know what parameter to compare with. I think if we go this way at all it should be a function provided my the user.

However, I'm not against having a couple pre-made functions available on the instance. (I've already done something similar for `keep-alive` routes).

**Comment by Chaphasilor** [comment]
Okay, here's another idea:

What if we specify the shared elements inside the route target? So inside the `to` prop of a `<router-link>`, etc.?  

I'm just brainstorming right now, but differentiating between global and local shared elements might help with that (i.e. a navbar would be global, but anything inside a router-link is local by default and is only cloned if the wrapping router link is activated, but not if any other router link is activated?)

**Comment by justintaddei** [comment]
That is a very interesting idea! Perhaps we could do something with that. How would work for the "Download Details" route where the shared element is outside of the `<router-link>` (the back button)?

**Comment by justintaddei** [comment]
Oh, you're saying that if the shared-element is in a `<router-link>`, and the link doesn't point to the upcoming route, then it should be ignored and all other shared-elements are left as usual? That actually sounds like it could work...

I'll play around with that idea and see what I come up with.

**Comment by Chaphasilor** [comment]
> That is a very interesting idea! Perhaps we could do something with that. How would work for the "Download Details" route where the shared element is outside of the `<router-link>` (the back button)?

The back button would be 'global', so it's always copied, as is currently the case.

 > Oh, you're saying that if the shared-element is in a <router-link>, and the link doesn't point to the upcoming route, then it should be ignored and all other shared-elements are left as usual?

Yep exactly. Just compare the router-link's route to the target route and then exclude any element that's not inside that router link and is also not global.

**Comment by Chaphasilor** [comment]
And the other idea (a bit more verbose) is listing any shared element you want to copy inside of the route object. So in a router link, you have a `to` prop, which is just an object. We should be able to add another attribute (maybe `shared`), which is just an array of `v-shared-element` IDs. This would mostly achieve the same as checking if shared elements are inside a router link, but is more flexible and also works using programmatic navigation without router links!

In your `SharedElementRouteGuard` you could then simply access `to.shared` and copy any element that's listed there!

**Comment by Chaphasilor** [comment]
Okay I just tested a bit more, and the delay is not affected by the number of cards on the screen...  
That means all the ideas we had might be good, but won't help with this issue! 😕

**Comment by justintaddei** [comment]
> I also noticed the click event is not delayed when 'going back' in history ($router.go(-1)) compared to using a router-link with :to={name: <PreviousRouteName>}.  
Very interesting 🤔.  
Is it possible another plugin is effecting it instead of `v-shared-element`?

> The transition is still delayed though?  
Oh wait, so you're saying `v-shared-element` is delayed but not the actual route change?

> Okay I just tested a bit more, and the delay is not affected by the number of cards on the screen...

My first thought is that you still have `restrictToViewport`enabled. Hopefully I'm right because that would make this a lot less weird :)

**Comment by justintaddei** [comment]
> Yep exactly. Just compare the router-link's route to the target route and then exclude any shared element that's not inside that router link and is also not global.

I really like is idea. I'll start experimenting shortly.

> In your SharedElementRouteGuard you could then simply access to.shared and copy any element that's listed there!  
This seems a little _too_ verbose. And, correct me if I'm wrong, but I don't think that would work for shared-elements with dynamic IDs?

**Comment by Chaphasilor** [comment]
> > The transition is still delayed though?
> 
> Oh wait, so you're saying `v-shared-element` is delayed but not the actual route change?

I'm saying the transition is delayed but the click event (e.g. vibration) isn't. The route change is probably delayed as well...

> > Okay I just tested a bit more, and the delay is not affected by the number of cards on the screen...
> 
> My first thought is that you still have `restrictToViewport` enabled. Hopefully I'm right because that would make this a lot less weird :)

I do, but the number of elements inside the viewport varies, so shouldn't the performance vary too?

**Comment by justintaddei** [comment]
> I do, but the number of elements inside the viewport varies, so shouldn't the performance vary too?

Yes, it should. That is very strange.  
I'll have to do some testing later today and see if I can reproduce that.

Do you know how to use the Performance panel in DevTools? If so, would you mind exporting a recording of you switching routes a couple times? That would help me see which function is taking the longest.

**Comment by Chaphasilor** [comment]
> Do you know how to use the Performance panel in DevTools? If so, would you mind exporting a recording of you switching routes a couple times? That would help me see which function is taking the longest.

Sure no problem!

**Comment by Chaphasilor** [comment]
Here you go: https://gofile.io/d/nq69NW

You can also check out the project at https://github.com/Chaphasilor/njoy-frontend/tree/snappy_transitions :)

**Comment by justintaddei** [comment]
Thank you! That will help a lot. I'll be able to work on it in a couple hours.

**Comment by justintaddei** [comment]
Okay. I had a chance to look over that performance profile.

It seems as though the majority of the time spent is on one to two nodes with a deep subtree. This might explain why adding more shared-elements didn't affect the overall performance very much. How to mitigate that... I don't really know yet.

To confirm that this is in fact the issue, will you globally disable  `includeChildren` and just tell me roughly how long the click event blocks the main thread for when opening the card? Right now it's about 400ms and I'm hoping that disabling that will drop it to about 100ms. If that in fact works, perhaps some kind of subtree depth limit might be the way to go 🤷‍♂️

**Comment by Chaphasilor** [comment]
I can upload you another profile later :)  
(Not totally sure how you count the ms, that's why)

Might it be that recursive copying isn't needed here at all? 

I'm also wondering how limiting the depth would affect the result, and if this could be then properly mitigated by introducing additional shared elements at lower levels?

**Comment by Chaphasilor** [comment]
Here's the profile: https://gofile.io/d/O1k7hY  
Seems to help a lot with the delay, but it's not suited for what I want to achieve :/

**Comment by justintaddei** [comment]
It's definitely not as appealing. I was justing trying to isolate the cause of such a long delay.

Thank you for sending that profile. I'll compare the two and see if I can make any optimizations that don't effect the appearance the animation. If not, the next best thing would likely be an option to limit the depth of the cloned subtree.

**Comment by Chaphasilor** [comment]
Alright, thank you for your support! :D

**Comment by justintaddei** [comment]
The current is about as optimized as it's going to get (it seems it the native `cloneNode` and `window.getComputedStyle` methods that make up the majority of the overhead)

I'm currently working on prototype using `requestIdleCallback` that seems promising except that Safari doesn't support it yet. I'll keep you posted.

I also like the idea of a `restrictToRoutes` option (in addition?). I'll see how well the idle callback method works first.

**Comment by Chaphasilor** [comment]
I guess it's no big deal if Safari doesn't support it yet, because it doesn't add functionality, but only improves performance...  
It's sad that Sufferi strikes again, but that is to be expected...

A way to restrict the copying seems useful as well to me, I'm just not sure listing all routes is a good approach. A callback function should to the trick though?

**Comment by justintaddei** [comment]
I agree about Safari. I'm just going to chock it up to "progressive enhancement."

As for `restrictToRoutes`, I think there was some miscommunication. How I imagine the feature working is that by default the current behavior is maintained, but if you want to limit a given shared-element to particular route(s), you can set `restrictToRoutes` to either an array of the "allowed" route(s), or a function that returns either true or false based on user-defined criteria (much the same as `Array.prototype.filter`).  

When you mentioned making the filter function internal, it gave me an idea for a built-in method (an instance method like `$keepSharedElementAlive`) that takes the name of the route param, used for the _id_, as an argument. That way it could check if the shared-element id matches the upcoming route's id and automatically decide what to do.

```
​<​Component​
  ​v-shared-element:​[`​download-​${​id​}`]=​"​{​
​    restrictToRoutes: ['/about', '/details']​

    // or​    restrictToRoutes: (route, id) => id.includes(route.params.id)​

    // or
    restrictToRoutes: $sharedElement.restrictTo('id')
​  }​"​
/>
```

(The method name could use some work, but you get the idea)

**Comment by Chaphasilor** [comment]
Yeah you should probably pass the `from` and `to` objects to that filter function.

As for the internal filter, requiring the shared element id to match the route id probably isn't ideal because it's not very flexible. Or am I misunderstanding your proposal?

**Comment by justintaddei** [comment]
> Yeah you should probably pass the from and to objects to that filter function.  

Definitely! Perhaps the signature should be `(from, to, id) => boolean`? You need the `id` of the shared-element an order for it to be useful.

> As for the internal filter, requiring the shared element id to match the route id probably isn't ideal because it's not very flexible. Or am I misunderstanding your proposal?

So, what I'm thinking is that the internal filter should check if the id of the shared-element (in the example above, that would be `"download-<id string>"`) contains the id of the route. So not `routeId === sharedElementId`, rather `sharedElementId.indexOf(routeId) !== -1`. That would allow multiple shared-elements to match a single route.

**Comment by justintaddei** [comment]
On another note, going from your "Download Details" route to the "Progress" route could be improved by reducing the number of shared-elements present. Currently, every `<InfoLine />` is a shared-element but only 2 actually need to be.

The red outlines denote a shared-element:  
![image](https://user-images.githubusercontent.com/16705594/97088678-21519700-15f8-11eb-9390-dca51aac3316.png)

**Comment by Chaphasilor** [comment]
> Definitely! Perhaps the signature should be `(from, to, id) => boolean`? You need the `id` of the shared-element an order for it to be useful.

If the function is defined on the directive declaration, the user has access to the id anyway.  
And in my case I don't need the full shared element id, but only part of it. If you want I can send you an example of what I mean later.

> So, what I'm thinking is that the internal filter should check if the id of the shared-element (in the example above, that would be `"download-<id string>"`) contains the id of the route. So not `routeId === sharedElementId`, rather `sharedElementId.indexOf(routeId) !== -1`. That would allow multiple shared-elements to match a single route.

That might still require changes to the routes. What if a route simply doesn't contain any id?

**Comment by Chaphasilor** [comment]
> On another note, going from your "Download Details" route to the "Progress" route could be improved by reducing the number of shared-elements present. Currently, every `<InfoLine />` is a shared-element but only 2 actually need to be.

Yeah, some aren't required (about half). Do you think this will improve the performance noticeably?

**Comment by justintaddei** [comment]
It might. I'll try it myself and let you know a little later

**Comment by Chaphasilor** [comment]
Oh awesome, thanks a lot!

**Comment by justintaddei** [comment]
Surprisingly, the use of `requestIdleCallback` actually made to performance worse... I'm not entirely sure why though. I'm having a lot better luck with `restrictToRoutes` though. Trying to find a solution that isn't too verbose. I'll keep this thread updated as I continue to experiment

**Comment by justintaddei** [comment]
Using `restrictToRoutes` reduces the input delay from the `400ms` that it was to only around `230ms` (which is still twice what I would consider acceptable).

I'm going to continue working on the `requestIdleCallback` approach and if I can get that delay any lower.

**Comment by justintaddei** [comment]
If you want to try out the `restrictToRoutes` feature, you can clone the [feature/restrict-to-routes](https://github.com/justintaddei/v-shared-element/tree/feature/restrict-to-routes) branch and run `npm i && npm link` in that directory and then run `npm link v-shared-element` in your project directory.

**Comment by justintaddei** [comment]
I just released version 3.0.0! It uses the new version of illusory (the main reason it was a breaking change) and a few of the defaults were changed. You shouldn't experience any problems with upgrading. It also adds the `restrictToRoutes` option that I was able to use to cut the blocking-time during navigation in half for your app.

I'm going to keep this issue open since I'm still working on an implementation that makes use of `requestIdleCallback`.  
I will continue to keep this thread updated as that progresses.

In the meantime, try out `restrictToRoutes` and let me know if you have any difficulties!

**Comment by Chaphasilor** [comment]
Awesome, gonna update it now and see how it goes!

**Comment by Chaphasilor** [comment]
Okay, I've tried this out now, but somehow I'm not seeing any improvement at all (at least nothing noticeable) :/
I've used the `restrictToRoutes` parameter to only clone the element if the download IDs between the routes match and also used a generic function that always returns `false` to 'disable' some of the unneeded shared elements (vue directives can't be applied conditionally afaik, so that was the only possibility I saw to achieve this...)

You know where to find the source code, am I missing something obvious? Or is the delay somehow shorter internally, but the rendering isn't affected?

I hope I don't disappoint you with this reply :(

**Comment by justintaddei** [comment]
Hm. I'm experiencing some extremely strange behavior from v3 that I did not notice at first. I assume it is something that was introduced in illusory v2 but whatever it is, it broke the example page. I'm unpublishing v3 until I can resolve these issues.

**Comment by justintaddei** [comment]
Finally! Sorry for such a HUGE delay on this. I've been super busy lately traveling and looking for work (I just turned 20).

I just released v3 again!

**Comment by Chaphasilor** [comment]
Hey, sorry I didn't even see your previous comment 😅 

Glad to know you sorted it out, and don't worry about the delay, I have too many side projects anyway :D 

Oh and happy birthday! 🥳

**Comment by justintaddei** [comment]
Thank you!

Also, I've enabled GitHub Discussions for the repo if you ever have any questions that don't warrant creating an issue  💬
