### ISSUE TITLE
Update Illusory v2.0.2

### ISSUE THREAD

**Issue by VietKhangLH** [justintaddei/v-shared-element#22]
Hello !
I tried to use it with Illusory v2.0.2, to use relativeTo params.
Unfortunatly, there is an error from "processClone" function while instanciating IllusoryElement.

In new Illusory version, processClone return null if processClone returns null.
I tried to quickfix it by returning a node in process clone, but it brings some weird artifacts...

Have you any idea of how to do it properly ?

**Comment by justintaddei** [comment]
I have an experimental v3 branch that I'm working on. I maintain both packages but I've had some unforeseen difficulties upgrading v-shared-element to illusory v2. What kind of artifacts are you seeing?

**Comment by VietKhangLH** [comment]
With 2 pages :
- one with a list of v-shared-element with id,
- one with a v-shared-element that receive that id dynamically

The first transition works, but then, the others are shifted by a certain offset

**Comment by justintaddei** [comment]
Thank you. I will look into that today.

I intend to release v3 very soon if I can work out all of these little quirks.

**Comment by justintaddei** [comment]
I had to take an unexpected flight and will be away for a week, I will try to work on this sooner but in all likelihood it will have to wait until I return.

**Comment by VietKhangLH** [comment]
Hello,
Thank you for your message.
I hope you are doing fine IRL.
Thank you for you work you have done already :)

Le sam. 5 déc. 2020 à 02:13, Justin Taddei <notifications@github.com> a
écrit :

**Comment by justintaddei** [comment]
Hey! Sorry, I was out of town a lot longer than I thought I would be, but I'm back now.

I should have an update ready in a couple days!

**Comment by VietKhangLH** [comment]
Awesome, thanks for the update!

Le lun. 21 déc. 2020 à 22:56, Justin Taddei <notifications@github.com> a
écrit :

**Comment by justintaddei** [comment]
`v-shared-element@3.0.1` has been released, powered by `illusory@2.0.3`! 

Let me know if you have any issues updating.   I've also enabled _GitHub Discussions_ for the repo if you have any questions!
