### ISSUE TITLE
index.js:239 Uncaught TypeError: Cannot set property '$illusory' of undefined

### ISSUE THREAD

**Issue by guepejuang** [justintaddei/v-shared-element#24]
i use vue 3 + vite + composition API.

after run npm i v-shared-element then use v shared on my vue app, i found this error

index.js:239 Uncaught TypeError: Cannot set property '$illusory' of undefined

**Comment by justintaddei** [comment]
Unfortunately v-shared-element does not yet support Vue 3. I just started a new job so I haven't had a lot of free time to maintain this recently. I plan to upgrade it in the next couple of weeks.

I'll keep this issue open until then.

**Comment by nicolidin** [comment]
Yes, I have this exact same error with vue3!:( 

Are you working on it @justintaddei ??
@guepejuang Have you found a workaround?

**Comment by justintaddei** [comment]
I've been super busy lately but this project is definitely still maintained. If you create a PR I will merge it.

**Comment by justintaddei** [comment]
This is currently being worked on. I hope to have an update out shortly with support for Vue3!
