### ISSUE TITLE
Just cloned the example branch - there's 1009 vulnerabilities (718 high)

### ISSUE THREAD

**Issue by liamb13** [justintaddei/v-shared-element#27]
What's being used that's causing this? It seems extremely high.

**Comment by liamb13** [comment]
Running npm audit -fix resolved 999 of them. I'm only submitting this issue as I don't recall seeing anything quite as high

**Comment by justintaddei** [comment]
`npm audit fix` seems to break the page, but I'm not sure why. It screws up hydration of the server-side rendered markup for some reason. Seeing as this is just the example page, it isn't a high priority for me. I will come back to this another time.
