### ISSUE TITLE
opacity transition when using includeChildren

### ISSUE THREAD

**Issue by 719media** [justintaddei/v-shared-element#4]
Is there a way to avoid the opacity transition when using includeChildren?

See
https://codesandbox.io/s/sharedelementtransition-opacity-question-jqzj8

**Comment by justintaddei** [comment]
Currently, no.

If the `v-shared-element` directive is on an `<img>` tag, however, the opacity blend will be disabled (it's actually more complex. See below). This is due to the behavior of [illusory](https://github.com/justintaddei/illusory) (the library that handles the actual transition of the elements). I can push an update to _illusory_ to add such capabilities. As far as _v-shared-element_, maybe a modifier for the directive would be a good idea? Something like `v-shared-element:id.opaque`

<br/>
<br/>
  
**Opacity blending**

If `_hasTransparentBackground` return true for the element we're transitioning into, the opacity will be animated.
```js
_hasTransparentBackground() {
    // getStyle just return the computed style for the given property.
    const rgba = parseRGBA(this.getStyle('backgroundColor'))
    if (!rgba) return false

    // `<img>` elements have a transparent background by default
    // even if the image is fully opaque. If we report the background
    // as transparent the image will "flash" when transitioned.
    // This is the best thing I can think to do for now.
    // Later, some form of manual override would probably be useful.
    if (this.clone.tagName === 'IMG') return 0 < rgba.a && rgba.a < 1

    return rgba.a < 1
}
```

**Comment by 719media** [comment]
I definitely think that illusory should have an option to force this, seems like a very needed/useful option.
I think having the option available just as part of the options is sufficient. I think if you use a modifier, then it seems strange that some options are in the options json, and this new one is in a modifier. I think having

```
<div
  v-shared-element:profile="{
    easing: 'ease',
    duration: '300ms',
    endDuration: '150ms',
    zIndex: 1,
    compositeOnly: false,
    includeChildren: false,
    animateOpacity: false, // or whatever it should be called
  }"
></div>
```

is good and keeps the options together

**Comment by justintaddei** [comment]
Love it. I'll begin work on that soon and close this issue when it's released (probably in the same release as #2).

**Comment by justintaddei** [comment]
[illusory@1.3.0](https://www.npmjs.com/package/illusory) is now published.

It adds a new "ignore transparency" option:

```ts
/**
   * If `false` and the element we're transitioning **to** has a transparent background then
   * the element we're transitioning from will fade out.
   * If `true` the transparency of the element's background will be ignored.
   *
   * This can also be an array of tag names that should be ignored (e.g. `['img', 'button']`).
   * @default ['img']
   */
  ignoreTransparency: boolean | string[]
``` 

The question is, should we keep the name `ignoreTransparency` in v-shared-element, or would another name make more sense in this case?

**Comment by justintaddei** [comment]
I'm going to go ahead and keep the naming consistency with _illusory's_ `ignoreTransparency`.

**Comment by justintaddei** [comment]
Added option  `ignoreTransparency` in #8. It will ship with the next version.
