### ISSUE TITLE
How to properly animate text

### ISSUE THREAD

**Issue by 719media** [justintaddei/v-shared-element#5]
Have a look at
https://codesandbox.io/s/v-shared-element-text-transition-hrh9o?file=/src/views/About.vue

How is it possible to animate/transition the Home + About text (sliding left to right and vice versa). I understand that "text-align: right" won't do the trick because the containing box is still display block, but I thought that at least margins with display inline would have worked...

**Comment by justintaddei** [comment]
Try using `includeChildren: true`.

The text inside the heading is technically a child node

**Comment by justintaddei** [comment]
I'll make a mention in the docs of the things that you've gotten stuck on. Chances are others have too.

**Comment by justintaddei** [comment]
Here's a working example with text animation: https://codesandbox.io/embed/v-shared-element-text-transition-hrh9o?file=/src/main.js

All I changed was to globally enable `includeChildren`.

**Comment by 719media** [comment]
Ya makes sense, thanks for the clarification!
